export const names = [
    {
      id: "1",
      arabic: "ٱtلَّٰهُ",
      transliteration: "Allāh",
      german: "Der Einzige Gott",
      english: "The Only God",
    },
    {
      id: "2",
      arabic: "ٱلرَّحtمَٰنُ",
      transliteration: "Ar-Raḥmān",
      german: "Der Gnädige",
      english: "The Most Gracious",
    },
    {
      id: "3",
      arabic: "ٱلرَّحtيمُ",
      transliteration: "Ar-Raḥīm",
      german: "Der Barmherzige",
      english: "The Most Merciful",
    },
    {
      id: "4",
      arabic: "ٱلْمtلِكُ",
      transliteration: "Al-Malik",
      german: "Der König",
      english: "The Sovereign",
    },
    {
      id: "5",
      arabic: "ٱلْقُدُtوسُ",
      transliteration: "Al-Quddūs",
      german: "Der Heilige",
      english: "The Holy",
    },
    {
      id: "6",
      arabic: "ٱلسَtلَٰمُ",
      transliteration: "As-Salām",
      german: "Der Friedvolle",
      english: "The Source of Peace",
    },
    {
      id: "7",
      arabic: "ٱلْمُؤtمِنُ",
      transliteration: "Al-Muʾmin",
      german: "Der Glaubenswahrer",
      english: "The Guardian of Faith",
    },
    {
      id: "8",
      arabic: "ٱلْمُهَيtمِنُ",
      transliteration: "Al-Muhaymin",
      german: "Der Beschützer",
      english: "The Protector",
    },
    {
      id: "9",
      arabic: "ٱلْعَزtيزُ",
      transliteration: "Al-ʿAzīz",
      german: "Der Mächtige",
      english: "The Mighty",
    },
    {
      id: "10",
      arabic: "ٱلْجَبَtارُ",
      transliteration: "Al-Jabbār",
      german: "Der Gewaltige",
      english: "The Compeller",
    },
    {
      id: "11",
      arabic: "ٱلْمُتَكtبِّرُ",
      transliteration: "Al-Mutakabbir",
      german: "Der Stolze",
      english: "The Majestic",
    },
    {
      id: "12",
      arabic: "ٱلْخَtلِقُ",
      transliteration: "Al-Khāliq",
      german: "Der Schöpfer",
      english: "The Creator",
    },
    {
      id: "13",
      arabic: "ٱلْبَtرِئُ",
      transliteration: "Al-Bāriʾ",
      german: "Der Erschaffer",
      english: "The Maker",
    },
    {
      id: "14",
      arabic: "ٱلْمُصtوِّرُ",
      transliteration: "Al-Muṣawwir",
      german: "Der Formgeber",
      english: "The Fashioner",
    },
    {
      id: "15",
      arabic: "ٱلْغَفَtارُ",
      transliteration: "Al-Ghaffār",
      german: "Der Vergebende",
      english: "The Oft-Forgiving",
    },
    {
      id: "16",
      arabic: "ٱلْقَهَtارُ",
      transliteration: "Al-Qahhār",
      german: "Der Bezwingende",
      english: "The All-Subduing",
    },
    {
      id: "17",
      arabic: "ٱلْوَهَtابُ",
      transliteration: "Al-Wahhāb",
      german: "Der Geber",
      english: "The Bestower",
    },
    {
      id: "18",
      arabic: "ٱلرَّزَtاقُ",
      transliteration: "Ar-Razzāq",
      german: "Der Versorger",
      english: "The Provider",
    },
    {
      id: "19",
      arabic: "ٱلْفَتَtاحُ",
      transliteration: "Al-Fattāḥ",
      german: "Der Öffner",
      english: "The Opener",
    },
    {
      id: "20",
      arabic: "ٱلْعَلtيمُ",
      transliteration: "Al-ʿAlīm",
      german: "Der Wissende",
      english: "The All-Knowing",
    },
    {
      id: "21",
      arabic: "ٱلْقَtبِضُ",
      transliteration: "Al-Qābiḍ",
      german: "Der Zurückhalter",
      english: "The Withholder",
    },
    {
      id: "22",
      arabic: "ٱلْبَtسِطُ",
      transliteration: "Al-Bāsiṭ",
      german: "Der Ausdehner",
      english: "The Expander",
    },
    {
      id: "23",
      arabic: "ٱلْخَtفِضُ",
      transliteration: "Al-Khāfiḍ",
      german: "Der Erniedriger",
      english: "The Abaser",
    },
    {
      id: "24",
      arabic: "ٱلرَّtفِعُ",
      transliteration: "Ar-Rāfiʿ",
      german: "Der Erhöher",
      english: "The Exalter",
    },
    {
      id: "25",
      arabic: "ٱلْمtعِزُّ",
      transliteration: "Al-Muʿizz",
      german: "Der Ehrengeber",
      english: "The Giver of Honor",
    },
    {
      id: "26",
      arabic: "ٱلْمtذِلُّ",
      transliteration: "Al-Muẓill",
      german: "Der Demütiger",
      english: "The Humiliator",
    },
    {
      id: "27",
      arabic: "ٱلسَّمtيعُ",
      transliteration: "As-Samīʿ",
      german: "Der Hörende",
      english: "The All-Hearing",
    },
    {
      id: "28",
      arabic: "ٱلْبَصtيرُ",
      transliteration: "Al-Baṣīr",
      german: "Der Sehende",
      english: "The All-Seeing",
    },
    {
      id: "29",
      arabic: "ٱلْحtكَمُ",
      transliteration: "Al-Ḥakam",
      german: "Der Richter",
      english: "The Judge",
    },
    {
      id: "30",
      arabic: "ٱلْعtدْلُ",
      transliteration: "Al-ʿAdl",
      german: "Der Gerechte",
      english: "The Just",
    },
    {
      id: "31",
      arabic: "ٱللَّطtيفُ",
      transliteration: "Al-Laṭīf",
      german: "Der Feinfühlige",
      english: "The Subtle One",
    },
    {
      id: "32",
      arabic: "ٱلْخَبtيرُ",
      transliteration: "Al-Khabīr",
      german: "Der Kundige",
      english: "The All-Aware",
    },
    {
      id: "33",
      arabic: "ٱلْحَلtيمُ",
      transliteration: "Al-Ḥalīm",
      german: "Der Geduldige",
      english: "The Forbearing",
    },
    {
      id: "34",
      arabic: "ٱلْعَظtيمُ",
      transliteration: "Al-ʿAẓīm",
      german: "Der Erhabene",
      english: "The Magnificent",
    },
    {
      id: "35",
      arabic: "ٱلْغَفtورُ",
      transliteration: "Al-Ghafūr",
      german: "Der Verzeihende",
      english: "The All-Forgiving",
    },
    {
      id: "36",
      arabic: "ٱلشَّكtورُ",
      transliteration: "Ash-Shakūr",
      german: "Der Dankbare",
      english: "The Appreciative",
    },
    {
      id: "37",
      arabic: "ٱلْعtلِيُّ",
      transliteration: "Al-ʿAliyy",
      german: "Der Höchste",
      english: "The Most High",
    },
    {
      id: "38",
      arabic: "ٱلْكَبtيرُ",
      transliteration: "Al-Kabīr",
      german: "Der Große",
      english: "The Most Great",
    },
    {
      id: "39",
      arabic: "ٱلْحَفtيظُ",
      transliteration: "Al-Ḥafīẓ",
      german: "Der Bewahrer",
      english: "The Preserver",
    },
    {
      id: "40",
      arabic: "ٱلْمُقtيتُ",
      transliteration: "Al-Muqīt",
      german: "Der Ernährer",
      english: "The Sustainer",
    },
    {
      id: "41",
      arabic: "ٱلْحَسtيبُ",
      transliteration: "Al-Ḥasīb",
      german: "Der Abrechner",
      english: "The Reckoner",
    },
    {
      id: "42",
      arabic: "ٱلْجَلtيلُ",
      transliteration: "Al-Jalīl",
      german: "Der Majestätische",
      english: "The Majestic",
    },
    {
      id: "43",
      arabic: "ٱلْكَرtيمُ",
      transliteration: "Al-Karīm",
      german: "Der Großzügige",
      english: "The Generous",
    },
    {
      id: "44",
      arabic: "ٱلرَّقtيبُ",
      transliteration: "Ar-Raqīb",
      german: "Der Wachsame",
      english: "The Watchful",
    },
    {
      id: "45",
      arabic: "ٱلْمُجtيبُ",
      transliteration: "Al-Mujīb",
      german: "Der Erhörer",
      english: "The Responsive",
    },
    {
      id: "46",
      arabic: "ٱلْوَtسِعُ",
      transliteration: "Al-Wāsiʿ",
      german: "Der Allumfassende",
      english: "The All-Encompassing",
    },
    {
      id: "47",
      arabic: "ٱلْحَكtيمُ",
      transliteration: "Al-Ḥakīm",
      german: "Der Weise",
      english: "The All-Wise",
    },
    {
      id: "48",
      arabic: "ٱلْوَدtودُ",
      transliteration: "Al-Wadūd",
      german: "Der Liebende",
      english: "The Loving",
    },
    {
      id: "49",
      arabic: "ٱلْمَجtيدُ",
      transliteration: "Al-Majīd",
      german: "Der Ruhmreiche",
      english: "The Glorious",
    },
    {
      id: "50",
      arabic: "ٱلْبَtعِثُ",
      transliteration: "Al-Bāʿith",
      german: "Der Erwecker",
      english: "The Resurrector",
    },
    {
      id: "51",
      arabic: "ٱلشَّهtيدُ",
      transliteration: "Ash-Shahīd",
      german: "Der Zeuge",
      english: "The Witness",
    },
    {
      id: "52",
      arabic: "ٱلtحَقُّ",
      transliteration: "Al-Ḥaqq",
      german: "Die Wahrheit",
      english: "The Truth",
    },
    {
      id: "53",
      arabic: "ٱلْوَكtيلُ",
      transliteration: "Al-Wakīl",
      german: "Der Sachwalter",
      english: "The Trustee",
    },
    {
      id: "54",
      arabic: "ٱلْقtوِيُّ",
      transliteration: "Al-Qawiyy",
      german: "Der Starke",
      english: "The All-Strong",
    },
    {
      id: "55",
      arabic: "ٱلْمَتtينُ",
      transliteration: "Al-Matīn",
      german: "Der Feste",
      english: "The Firm",
    },
    {
      id: "56",
      arabic: "ٱلْوtلِيُّ",
      transliteration: "Al-Waliyy",
      german: "Der Freund",
      english: "The Protecting Friend",
    },
    {
      id: "57",
      arabic: "ٱلْحَمtيدُ",
      transliteration: "Al-Ḥamīd",
      german: "Der Preiswürdige",
      english: "The Praiseworthy",
    },
    {
      id: "58",
      arabic: "ٱلْمُحtصِي",
      transliteration: "Al-Muḥṣī",
      german: "Der Zählende",
      english: "The Accounter",
    },
    {
      id: "59",
      arabic: "ٱلْمُبtدِئُ",
      transliteration: "Al-Mubdiʾ",
      german: "Der Urheber",
      english: "The Originator",
    },
    {
      id: "60",
      arabic: "ٱلْمُعtيدُ",
      transliteration: "Al-Muʿīd",
      german: "Der Wiederhersteller",
      english: "The Restorer",
    },
    {
      id: "61",
      arabic: "ٱلْمُحtيِي",
      transliteration: "Al-Muḥyī",
      german: "Der Lebengeber",
      english: "The Giver of Life",
    },
    {
      id: "62",
      arabic: "ٱلْمُمtيتُ",
      transliteration: "Al-Mumīt",
      german: "Der Todbringer",
      english: "The Bringer of Death",
    },
    {
      id: "63",
      arabic: "ٱلtحَيُّ",
      transliteration: "Al-Ḥayy",
      german: "Der Lebendige",
      english: "The Ever-Living",
    },
    {
      id: "64",
      arabic: "ٱلْقَيُtومُ",
      transliteration: "Al-Qayyūm",
      german: "Der Selbstbestehende",
      english: "The Sustainer of All",
    },
    {
      id: "65",
      arabic: "ٱلْوَtجِدُ",
      transliteration: "Al-Wājid",
      german: "Der Findende",
      english: "The Finder",
    },
    {
      id: "66",
      arabic: "ٱلْمَtجِدُ",
      transliteration: "Al-Mājid",
      german: "Der Edle",
      english: "The Noble",
    },
    {
      id: "67",
      arabic: "ٱلْوَtحِدُ",
      transliteration: "Al-Wāḥid",
      german: "Der Einzige",
      english: "The One",
    },
    {
      id: "68",
      arabic: "ٱلْأtحَدُ",
      transliteration: "Al-Aḥad",
      german: "Der Einzigartige",
      english: "The Unique",
    },
    {
      id: "69",
      arabic: "ٱلصَtمَدُ",
      transliteration: "Aṣ-Ṣamad",
      german: "Der Unabhängige",
      english: "The Eternal Refuge",
    },
    {
      id: "70",
      arabic: "ٱلْقَtدِرُ",
      transliteration: "Al-Qādir",
      german: "Der Fähige",
      english: "The All-Capable",
    },
    {
      id: "71",
      arabic: "ٱلْمُقْتtدِرُ",
      transliteration: "Al-Muqtadir",
      german: "Der Allmächtige",
      english: "The All-Powerful",
    },
    {
      id: "72",
      arabic: "ٱلْمُقtدِّمُ",
      transliteration: "Al-Muqaddim",
      german: "Der Voranbringer",
      english: "The Expediter",
    },
    {
      id: "73",
      arabic: "ٱلْمُؤtخِّرُ",
      transliteration: "Al-Muʾakhkhir",
      german: "Der Zurücksteller",
      english: "The Delayer",
    },
    {
      id: "74",
      arabic: "ٱلْأtوَّلُ",
      transliteration: "Al-Awwal",
      german: "Der Erste",
      english: "The First",
    },
    {
      id: "75",
      arabic: "ٱلْtخِرُ",
      transliteration: "Al-Ākhir",
      german: "Der Letzte",
      english: "The Last",
    },
    {
      id: "76",
      arabic: "ٱلظَّtهِرُ",
      transliteration: "Aẓ-Ẓāhir",
      german: "Der Offenbare",
      english: "The Manifest",
    },
    {
      id: "77",
      arabic: "ٱلْبَtطِنُ",
      transliteration: "Al-Bāṭin",
      german: "Der Verborgene",
      english: "The Hidden",
    },
    {
      id: "78",
      arabic: "ٱلْوَtلِي",
      transliteration: "Al-Wālī",
      german: "Der Lenker",
      english: "The Governor",
    },
    {
      id: "79",
      arabic: "ٱلْمُتَعَtلِي",
      transliteration: "Al-Mutaʿālī",
      german: "Der Erhabene",
      english: "The Most Exalted",
    },
    {
      id: "80",
      arabic: "ٱلtبَرُّ",
      transliteration: "Al-Barr",
      german: "Der Gütige",
      english: "The Beneficent",
    },
    {
      id: "81",
      arabic: "ٱلتَّوَtابُ",
      transliteration: "At-Tawwāb",
      german: "Der Reue-Annehmende",
      english: "The Acceptor of Repentance",
    },
    {
      id: "82",
      arabic: "ٱلْمُنْتtقِمُ",
      transliteration: "Al-Muntaqim",
      german: "Der Rächer",
      english: "The Avenger",
    },
    {
      id: "83",
      arabic: "ٱلْعtفُوُّ",
      transliteration: "Al-ʿAfuww",
      german: "Der Verzeihende",
      english: "The Pardoner",
    },
    {
      id: "84",
      arabic: "ٱلرَّءtوفُ",
      transliteration: "Ar-Raʾūf",
      german: "Der Milde",
      english: "The Kind",
    },
    {
      id: "85",
      arabic: "مَالِكُ ٱلْمtلْكِ",
      transliteration: "Mālik-ul-Mulk",
      german: "Der Besitzer des Königreichs",
      english: "The Owner of Sovereignty",
    },
    {
      id: "86",
      arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرtامِ",
      transliteration: "Dhul-Jalāli wal-Ikrām",
      german: "Der Herr der Herrlichkeit und Ehre",
      english: "The Lord of Majesty and Bounty",
    },
    {
      id: "87",
      arabic: "ٱلْمُقtسِطُ",
      transliteration: "Al-Muqsiṭ",
      german: "Der Gerechte",
      english: "The Equitable",
    },
    {
      id: "88",
      arabic: "ٱلْجَtمِعُ",
      transliteration: "Al-Jāmiʿ",
      german: "Der Sammler",
      english: "The Gatherer",
    },
    {
      id: "89",
      arabic: "ٱلْغtنِيُّ",
      transliteration: "Al-Ghaniyy",
      german: "Der Unbedürftige",
      english: "The Self-Sufficient",
    },
    {
      id: "90",
      arabic: "ٱلْمُغtنِي",
      transliteration: "Al-Mughnī",
      german: "Der Reichmacher",
      english: "The Enricher",
    },
    {
      id: "91",
      arabic: "ٱلْمَtنِعُ",
      transliteration: "Al-Māniʿ",
      german: "Der Verhinderer",
      english: "The Preventer",
    },
    {
      id: "92",
      arabic: "ٱلضَtارُّ",
      transliteration: "Aḍ-Ḍārr",
      german: "Der Schädigende",
      english: "The Distresser",
    },
    {
      id: "93",
      arabic: "ٱلنَّtفِعُ",
      transliteration: "An-Nāfiʿ",
      german: "Der Nützende",
      english: "The Benefiter",
    },
    {
      id: "94",
      arabic: "ٱلنُtورُ",
      transliteration: "An-Nūr",
      german: "Das Licht",
      english: "The Light",
    },
    {
      id: "95",
      arabic: "ٱلْهَtدِي",
      transliteration: "Al-Hādī",
      german: "Der Führer",
      english: "The Guide",
    },
    {
      id: "96",
      arabic: "ٱلْبَدtيعُ",
      transliteration: "Al-Badīʿ",
      german: "Der Erfinder",
      english: "The Incomparable",
    },
    {
      id: "97",
      arabic: "ٱلْبَtقِي",
      transliteration: "Al-Bāqī",
      german: "Der Bleibende",
      english: "The Everlasting",
    },
    {
      id: "98",
      arabic: "ٱلْوَارِثُ",
      transliteration: "Al-Wārith",
      german: "Der Erbe",
      english: "The Inheritor",
    },
    {
      id: "99",
      arabic: "ٱلرَّشtيدُ",
      transliteration: "Ar-Rashīd",
      german: "Der Rechtleitende",
      english: "The Guide to the Right Path",
    },
  ];